CREATE TABLE PWM_INFO (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  URL NVARCHAR(500),
  USERNAME NVARCHAR(500),
  PASSWORD NVARCHAR(500) NOT NULL,
  TYPE VARCHAR(50) NOT NULL
);

CREATE TABLE PWM_SK (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  PEM TEXT NOT NULL,
  PUB TEXT NOT NULL
);

CREATE TABLE PWM_USER (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  PASSWORD NVARCHAR(100) NOT NULL
);